---
- hosts: oracle
  become:
    true
  vars:
    nginx_user: nginx  
  roles:
   - sendkey
   - epel
   - nginx

- hosts: debian
  become:
    true
  vars:
    nginx_user: www-data  
  roles:
   - sendkey
   - nginx

