---
- hosts: oracle
  become:
    true
#  become_method:
#    su
#  become_user:
#    root
#  remote_user:
#    ansible
  roles:
   - epel
   - nginx

- hosts: debian
  become:
    true
#  become_method:
#    sudo
#  become_user:
#    root
#  remote_user:
#    ansible
  roles:
   - nginx

