- name: Replace nginx.conf
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf

- name: Replace index.html
  template:
    src=templates/index.html
    dest=/usr/share/nginx/html/index.html


